# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e65f41ac752b00dca56f161d13c29c2e6ef23bd5797e87cbfe1beed8edcee51abdcac8d5d064c7287d46de808100600067deb3f84cb500a9d1a51316b5992cc

test:
  secret_key_base: c709501cb750c6721a80b680e8c8cebd23729fc52a0ba8cfc6d1bcc9c1ced5f1d4e9fabb0e1e050783ee6814702293a0d0757d7170125499577c9728e0df85c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
